name: null_wallet_ercbase
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  web3dart: ^2.2.0
  bip39: ^1.0.6
  bip32: ^2.0.0
  hex: ^0.2.0
  secp256k1: ^0.3.0
  http: ^0.13.3
  equatable: ^2.0.3
  json_annotation: ^4.1.0

dev_dependencies:
  pedantic: ^1.10.0
  test: ^1.16.0
  build_runner: ^2.0.0
  json_serializable: ^5.0.0
